--  Generate SQL 
--  Version:                   	V7R5M0 220415 
--  Generated on:              	05/14/26 16:10:43 
--  Relational Database:       	A12456DF 
--  Standards Option:          	Db2 for i 
CREATE TABLE PFWF0125.COACMAST ( 
--  SQL150B   10   REUSEDLT(*NO) in table COACMAST in PFWF0125 ignored. 
	CA_STA FOR COLUMN CASTA      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	CA_CO FOR COLUMN CACO       CHAR(2) CCSID 37 NOT NULL DEFAULT '' , 
	CA_CC FOR COLUMN CACC       CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	CA_ACC FOR COLUMN CAACC      CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	CA_DIV FOR COLUMN CADIV      CHAR(2) CCSID 37 NOT NULL DEFAULT '' , 
	CA_FILB FOR COLUMN CAFILB     CHAR(78) CCSID 37 NOT NULL DEFAULT '' , 
	CA_CGT FOR COLUMN CACGT      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLIC FOR COLUMN CAGLIC     CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLIA FOR COLUMN CAGLIA     CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLCC FOR COLUMN CAGLCC     CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLCA FOR COLUMN CAGLCA     CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLCP FOR COLUMN CAGLCP     DECIMAL(5, 3) NOT NULL DEFAULT 0 , 
	CA_GSC2 FOR COLUMN CAGSC2     CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GSA2 FOR COLUMN CAGSA2     CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GSC3 FOR COLUMN CAGSC3     CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GSA3 FOR COLUMN CAGSA3     CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GSC5 FOR COLUMN CAGSC5     CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GSA5 FOR COLUMN CAGSA5     CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GSC7 FOR COLUMN CAGSC7     CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GSA7 FOR COLUMN CAGSA7     CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GSC8 FOR COLUMN CAGSC8     CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GSA8 FOR COLUMN CAGSA8     CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	CA_CHT FOR COLUMN CACHT      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	CA_SLC FOR COLUMN CASLC      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	CA_SLS FOR COLUMN CASLS      DECIMAL(7, 0) NOT NULL DEFAULT 0 , 
	CA_FILD FOR COLUMN CAFILD     CHAR(7) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLWC FOR COLUMN CAGLWC     CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLWA FOR COLUMN CAGLWA     CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLC1 FOR COLUMN CAGLC1     CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLA1 FOR COLUMN CAGLA1     CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLC2 FOR COLUMN CAGLC2     CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLA2 FOR COLUMN CAGLA2     CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLC3 FOR COLUMN CAGLC3     CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLA3 FOR COLUMN CAGLA3     CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLC4 FOR COLUMN CAGLC4     CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLA4 FOR COLUMN CAGLA4     CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	CA_FILC FOR COLUMN CAFILC     CHAR(151) CCSID 37 NOT NULL DEFAULT '' , 
	CA_EAR FOR COLUMN CAEAR      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	CA_EWG FOR COLUMN CAEWG      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	CA_IAC FOR COLUMN CAIAC      CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	CA_IAA FOR COLUMN CAIAA      CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	CA_POR FOR COLUMN CAPOR      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLFC FOR COLUMN CAGLFC     CHAR(4) CCSID 37 NOT NULL DEFAULT '' , 
	CA_GLFA FOR COLUMN CAGLFA     CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	CA_BRT FOR COLUMN CABRT      CHAR(9) CCSID 37 NOT NULL DEFAULT '' , 
	CA_BAC FOR COLUMN CABAC      CHAR(17) CCSID 37 NOT NULL DEFAULT '' , 
	CA_YTD FOR COLUMN CAYTD      DECIMAL(13, 2) NOT NULL DEFAULT 0 , 
--  SQL150D   10   EDTCDE in column CA_YTD ignored. 
	CA_CUR FOR COLUMN CACUR      DECIMAL(13, 2) NOT NULL DEFAULT 0 , 
--  SQL150D   10   EDTCDE in column CA_CUR ignored. 
	CA_L12 FOR COLUMN CAL12      DECIMAL(13, 2) NOT NULL DEFAULT 0 , 
--  SQL150D   10   EDTCDE in column CA_L12 ignored. 
	CA_CNHA FOR COLUMN CACNHA     CHAR(6) CCSID 37 NOT NULL DEFAULT '' , 
	UPDATE_IDENT FOR COLUMN @@UPID     DECIMAL(7, 0) NOT NULL DEFAULT 0 , 
	PRIMARY KEY( CA_CO , CA_CC , CA_ACC , CA_DIV ) )   
	  
	RCDFMT COACMAST   ; 
  
--  SQL150A   30   System trigger QSYS_TRIG_PFWF0125___COACMAST___000001 in PFWF0125 ignored. 
--  SQL150A   30   System trigger QSYS_TRIG_PFWF0125___COACMAST___000002 in PFWF0125 ignored. 
--  SQL150A   30   System trigger QSYS_TRIG_PFWF0125___COACMAST___000003 in PFWF0125 ignored. 
LABEL ON TABLE PFWF0125.COACMAST 
	IS 'Chart Of Accounts' ; 
  
LABEL ON COLUMN PFWF0125.COACMAST 
( CA_STA IS 'Status' , 
	CA_CO IS 'Co' , 
	CA_CC IS 'Cost                Ctr' , 
	CA_ACC IS 'Acct                Numb' , 
	CA_DIV IS 'Div' , 
	CA_FILB IS 'Filler' , 
	CA_CGT IS 'Application         Type' , 
	CA_GLIC IS 'Inv                 Cost                Ctr' , 
	CA_GLIA IS 'Parts               Inventory           Account' , 
	CA_GLCC IS 'Cost of Sales       Cost Center' , 
	CA_GLCA IS 'Cost of             Sales               Account' , 
	CA_GLCP IS 'Cost of Sales       Default %' , 
	CA_GSC2 IS 'Cash Cd 2           Sale Cst            Ctr' , 
	CA_GSA2 IS 'Cash Cd 2           Sale                Acct' , 
	CA_GSC3 IS 'Cash Cd 3           Sale Cst            Ctr' , 
	CA_GSA3 IS 'Cash Cd 3           Sale                Acct' , 
	CA_GSC5 IS 'Cash Cd 5           Sale Cst            Ctr' , 
	CA_GSA5 IS 'Cash Cd 5           Sale                Acct' , 
	CA_GSC7 IS 'Cash Cd 7           Sale Cst            Ctr' , 
	CA_GSA7 IS 'Cash Cd 7           Sale                Acct' , 
	CA_GSC8 IS 'Cash Cd 8           Sle Cst             Ctr' , 
	CA_GSA8 IS 'Cash Cd 8           Sale                Acct' , 
	CA_CHT IS 'Cust                Sls                 Hs Ty' , 
	CA_SLC IS 'Sub-Ledger          Code' , 
	CA_SLS IS 'Sub-Ledger          Seq #' , 
	CA_FILD IS 'Filler' , 
	CA_GLWC IS 'Rental              Depreciation        Cost Center' , 
	CA_GLWA IS 'Rental              Depreciation        Account' , 
	CA_GLC1 IS 'Sle Cst             Ctr Prc             Lvl 1' , 
	CA_GLA1 IS 'Sale Acct           Pricing             Level 1' , 
	CA_GLC2 IS 'Sle Cst             Ctr Prc             Lvl 2' , 
	CA_GLA2 IS 'Sale Acct           Pricing             Level 2' , 
	CA_GLC3 IS 'Sle Cst             Ctr Prc             Lvl 3' , 
	CA_GLA3 IS 'Sale Acct           Pricing             Level 3' , 
	CA_GLC4 IS 'Sle Cst             Ctr Prc             Lvl 4' , 
	CA_GLA4 IS 'Sale Acct           Pricing             Level 4' , 
	CA_FILC IS 'Filler' , 
	CA_EAR IS 'MyDealer            A/R                 Account' , 
	CA_EWG IS 'MyDealer            Equipment           Account' , 
	CA_IAC IS 'Inv Acc             Cost                Ctr' , 
	CA_IAA IS 'Inv Acc             Acc' , 
	CA_POR IS 'Create              P/O                 Receipt' , 
	CA_GLFC IS 'Alias               Cost                Center' , 
	CA_GLFA IS 'Alias               Account' , 
	CA_BRT IS 'Bank                Rtg#' , 
	CA_BAC IS 'Bank                Account             Number' , 
	CA_YTD IS 'YTD                 Amount' , 
	CA_CUR IS 'Current             YTD                 Balance' , 
	CA_L12 IS 'Last                12' , 
	CA_CNHA IS 'CNH                 Alias               Account' , 
	UPDATE_IDENT IS '  Update/           Identifier' ) ; 
  
LABEL ON COLUMN PFWF0125.COACMAST 
( CA_STA TEXT IS 'Status' , 
	CA_CO TEXT IS 'Company' , 
	CA_CC TEXT IS 'Cost Center' , 
	CA_ACC TEXT IS 'Account Number' , 
	CA_DIV TEXT IS 'Division' , 
	CA_FILB TEXT IS 'Filler' , 
	CA_CGT TEXT IS 'Application Type' , 
	CA_GLIC TEXT IS 'Parts Inventory Cost Center' , 
	CA_GLIA TEXT IS 'Parts Inventory Account' , 
	CA_GLCC TEXT IS 'Cost of Sales Cost Center' , 
	CA_GLCA TEXT IS 'Cost of Sales Account' , 
	CA_GLCP TEXT IS 'Cost of Sales Default %' , 
	CA_GSC2 TEXT IS 'Sale Cost Center - Cash Code 2' , 
	CA_GSA2 TEXT IS 'Sale Account - Cash Code 2' , 
	CA_GSC3 TEXT IS 'Sale Cost Center - Cash Code 3' , 
	CA_GSA3 TEXT IS 'Sale Account - Cash Code 3' , 
	CA_GSC5 TEXT IS 'Sale Cost Center - Cash Code 5' , 
	CA_GSA5 TEXT IS 'Sale Account - Cash Code 5' , 
	CA_GSC7 TEXT IS 'Sale Cost Center - Cash Code 7' , 
	CA_GSA7 TEXT IS 'Sale Account - Cash Code 7' , 
	CA_GSC8 TEXT IS 'Sale Cost Center - Cash Code 8' , 
	CA_GSA8 TEXT IS 'Sale Account - Cash Code 8' , 
	CA_CHT TEXT IS 'Customer Sales History Type' , 
	CA_SLC TEXT IS 'Sub-Ledger Code' , 
	CA_SLS TEXT IS 'Sub-Ledger Sequence Number' , 
	CA_FILD TEXT IS 'Filler' , 
	CA_GLWC TEXT IS 'Rental Depreciation Cost Center' , 
	CA_GLWA TEXT IS 'Rental Depreciation Account' , 
	CA_GLC1 TEXT IS 'Sale Cost Ctr Pricing Level 1' , 
	CA_GLA1 TEXT IS 'Sale Account Pricing Level 1' , 
	CA_GLC2 TEXT IS 'Sale Cost Ctr Pricing Level 2' , 
	CA_GLA2 TEXT IS 'Sale Account Pricing Level 2' , 
	CA_GLC3 TEXT IS 'Sale Cost Ctr Pricing Level 3' , 
	CA_GLA3 TEXT IS 'Sale Account Pricing Level 3' , 
	CA_GLC4 TEXT IS 'Sale Cost Ctr Pricing Level 4' , 
	CA_GLA4 TEXT IS 'Sale Account Pricing Level 4' , 
	CA_FILC TEXT IS 'Filler' , 
	CA_EAR TEXT IS 'MyDealer A/R Account' , 
	CA_EWG TEXT IS 'MyDealer Equipment Account' , 
	CA_IAC TEXT IS 'Inventory Accrual Cost Center' , 
	CA_IAA TEXT IS 'Inventory Accrual Account' , 
	CA_POR TEXT IS 'Create P/O Receipt' , 
	CA_GLFC TEXT IS 'Alias Cost Center' , 
	CA_GLFA TEXT IS 'Alias Account' , 
	CA_BRT TEXT IS 'Bank Routing #' , 
	CA_BAC TEXT IS 'Bank Account Number' , 
	CA_YTD TEXT IS 'YTD Amount' , 
	CA_CUR TEXT IS 'Current YTD Balance' , 
	CA_L12 TEXT IS 'Last 12 Months' , 
	CA_CNHA TEXT IS 'CNH Alias Account' , 
	UPDATE_IDENT TEXT IS 'Field update / access identifier' ) ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON PFWF0125.COACMAST TO HEARCHIVE WITH GRANT OPTION ; 
  
