--  Generate SQL 
--  Version:                   	V7R5M0 220415 
--  Generated on:              	05/14/26 16:13:02 
--  Relational Database:       	A12456DF 
--  Standards Option:          	Db2 for i 
CREATE TABLE PFWF0125.GLFIS ( 
--  SQL150B   10   REUSEDLT(*NO) in table GLFIS in PFWF0125 ignored. 
	GF_STA FOR COLUMN GFSTA      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	GF_CO FOR COLUMN GFCO       CHAR(2) CCSID 37 NOT NULL DEFAULT '' , 
	GF_DIV FOR COLUMN GFDIV      CHAR(2) CCSID 37 NOT NULL DEFAULT '' , 
	GF_GLA FOR COLUMN GFGLA      CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	GF_GLC FOR COLUMN GFGLC      CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	GF_YR FOR COLUMN GFYR       NUMERIC(4, 0) NOT NULL DEFAULT 0 , 
	GF_H1 FOR COLUMN GFH1       DECIMAL(13, 2) NOT NULL DEFAULT 0 , 
	GF_H2 FOR COLUMN GFH2       DECIMAL(13, 2) NOT NULL DEFAULT 0 , 
	GF_H3 FOR COLUMN GFH3       DECIMAL(13, 2) NOT NULL DEFAULT 0 , 
	GF_H4 FOR COLUMN GFH4       DECIMAL(13, 2) NOT NULL DEFAULT 0 , 
	GF_H5 FOR COLUMN GFH5       DECIMAL(13, 2) NOT NULL DEFAULT 0 , 
	GF_H6 FOR COLUMN GFH6       DECIMAL(13, 2) NOT NULL DEFAULT 0 , 
	GF_H7 FOR COLUMN GFH7       DECIMAL(13, 2) NOT NULL DEFAULT 0 , 
	GF_H8 FOR COLUMN GFH8       DECIMAL(13, 2) NOT NULL DEFAULT 0 , 
	GF_H9 FOR COLUMN GFH9       DECIMAL(13, 2) NOT NULL DEFAULT 0 , 
	GF_H10 FOR COLUMN GFH10      DECIMAL(13, 2) NOT NULL DEFAULT 0 , 
	GF_H11 FOR COLUMN GFH11      DECIMAL(13, 2) NOT NULL DEFAULT 0 , 
	GF_H12 FOR COLUMN GFH12      DECIMAL(13, 2) NOT NULL DEFAULT 0 , 
	UPDATE_IDENT FOR COLUMN @@UPID     DECIMAL(7, 0) NOT NULL DEFAULT 0 , 
	PRIMARY KEY( GF_CO , GF_DIV , GF_GLA , GF_GLC , GF_YR ) )   
	  
	RCDFMT GLFISR     ; 
  
LABEL ON TABLE PFWF0125.GLFIS 
	IS 'G/L History' ; 
  
LABEL ON COLUMN PFWF0125.GLFIS 
( GF_STA IS 'Sta' , 
	GF_CO IS 'Co' , 
	GF_DIV IS 'Div' , 
	GF_GLA IS 'Acc' , 
	GF_GLC IS 'Cost                Ctr' , 
	GF_YR IS 'Year' , 
	GF_H1 IS 'Month 1' , 
	GF_H2 IS 'Month 2' , 
	GF_H3 IS 'Month 3' , 
	GF_H4 IS 'Month 4' , 
	GF_H5 IS 'Month 5' , 
	GF_H6 IS 'Month 6' , 
	GF_H7 IS 'Month 7' , 
	GF_H8 IS 'Month 8' , 
	GF_H9 IS 'Month 9' , 
	GF_H10 IS 'Month 10' , 
	GF_H11 IS 'Month 11' , 
	GF_H12 IS 'Month 12' , 
	UPDATE_IDENT IS '  Update/           Identifier' ) ; 
  
LABEL ON COLUMN PFWF0125.GLFIS 
( GF_STA TEXT IS 'Status' , 
	GF_CO TEXT IS 'Company' , 
	GF_DIV TEXT IS 'Division' , 
	GF_GLA TEXT IS 'Account Number' , 
	GF_GLC TEXT IS 'Cost Ctr' , 
	GF_YR TEXT IS 'Fiscal Year (CCYY)' , 
	GF_H1 TEXT IS 'Month 1' , 
	GF_H2 TEXT IS 'Month 2' , 
	GF_H3 TEXT IS 'Month 3' , 
	GF_H4 TEXT IS 'Month 4' , 
	GF_H5 TEXT IS 'Month 5' , 
	GF_H6 TEXT IS 'Month 6' , 
	GF_H7 TEXT IS 'Month 7' , 
	GF_H8 TEXT IS 'Month 8' , 
	GF_H9 TEXT IS 'Month 9' , 
	GF_H10 TEXT IS 'Month 10' , 
	GF_H11 TEXT IS 'Month 11' , 
	GF_H12 TEXT IS 'Month 12' , 
	UPDATE_IDENT TEXT IS 'Field update / access identifier' ) ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON PFWF0125.GLFIS TO HEARCHIVE WITH GRANT OPTION ; 
  
