--  Generate SQL 
--  Version:                   	V7R5M0 220415 
--  Generated on:              	05/31/26 15:21:25 
--  Relational Database:       	A12456DF 
--  Standards Option:          	Db2 for i 
CREATE TABLE PFWF0125.YTDIST ( 
--  SQL150B   10   REUSEDLT(*NO) in table YTDIST in PFWF0125 ignored. 
	DN_RID FOR COLUMN DNRID      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	DN_CO FOR COLUMN DNCO       CHAR(2) CCSID 37 NOT NULL DEFAULT '' , 
	DN_VEN FOR COLUMN DNVEN      CHAR(6) CCSID 37 NOT NULL DEFAULT '' , 
	DN_DIV FOR COLUMN DNDIV      CHAR(2) CCSID 37 NOT NULL DEFAULT '' , 
	DN_TC FOR COLUMN DNTC       CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	DN_VCH FOR COLUMN DNVCH      CHAR(6) CCSID 37 NOT NULL DEFAULT '' , 
	DN_NME FOR COLUMN DNNME      CHAR(25) CCSID 37 NOT NULL DEFAULT '' , 
	DN_RR FOR COLUMN DNRR       CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	DN_FILA FOR COLUMN DNFILA     CHAR(6) CCSID 37 NOT NULL DEFAULT '' , 
	DN_GRS FOR COLUMN DNGRS      DECIMAL(11, 2) NOT NULL DEFAULT 0 , 
--  SQL150D   10   EDTCDE in column DN_GRS ignored. 
	DN_ACC FOR COLUMN DNACC      CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	DN_DNU FOR COLUMN DNDNU      CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	DN_CC FOR COLUMN DNCC       CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	DN_FILB FOR COLUMN DNFILB     CHAR(6) CCSID 37 NOT NULL DEFAULT '' , 
	DN_CGC FOR COLUMN DNCGC      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	DN_CGT FOR COLUMN DNCGT      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	DN_STA FOR COLUMN DNSTA      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	DN_ORD FOR COLUMN DNORD      CHAR(10) CCSID 37 NOT NULL DEFAULT '' , 
	DN_INV FOR COLUMN DNINV      CHAR(15) CCSID 37 NOT NULL DEFAULT '' , 
	DNFILD CHAR(20) CCSID 37 NOT NULL DEFAULT '' , 
	DN_PO FOR COLUMN DNPO       CHAR(10) CCSID 37 NOT NULL DEFAULT '' , 
	DN_POBR FOR COLUMN DNPOBR     CHAR(2) CCSID 37 NOT NULL DEFAULT '' , 
	DN_CER FOR COLUMN DNCER      NUMERIC(7, 6) NOT NULL DEFAULT 0 , 
	DN_DTI FOR COLUMN DNDTI      NUMERIC(8, 0) NOT NULL DEFAULT 0 , 
	DN_DTD FOR COLUMN DNDTD      NUMERIC(8, 0) NOT NULL DEFAULT 0 , 
	DN_CUS FOR COLUMN DNCUS      CHAR(10) CCSID 37 NOT NULL DEFAULT '' , 
	DN_TID FOR COLUMN DNTID      DECIMAL(18, 0) NOT NULL DEFAULT 0 , 
	DN_SEQ FOR COLUMN DNSEQ      NUMERIC(5, 0) NOT NULL DEFAULT 0 , 
	DN_UID FOR COLUMN DNUID      DECIMAL(18, 0) NOT NULL DEFAULT 0 , 
	DN_CHQ FOR COLUMN DNCHQ      CHAR(7) CCSID 37 NOT NULL DEFAULT '' , 
	DN_HDES FOR COLUMN DNHDES     CHAR(40) CCSID 37 NOT NULL DEFAULT '' , 
	UPDATE_IDENT FOR COLUMN @@UPID     DECIMAL(7, 0) NOT NULL DEFAULT 0 , 
	PRIMARY KEY( DN_TID , DN_SEQ ) )   
	  
	RCDFMT YTDISTR    ; 
  
LABEL ON TABLE PFWF0125.YTDIST 
	IS 'Year To Date A/P Distribution' ; 
  
LABEL ON COLUMN PFWF0125.YTDIST 
( DN_RID IS 'RID' , 
	DN_CO IS 'Co' , 
	DN_VEN IS 'Ven #' , 
	DN_DIV IS 'Div' , 
	DN_TC IS 'Trans               Code' , 
	DN_VCH IS 'Vch #' , 
	DN_NME IS 'Name' , 
	DN_RR IS 'RR' , 
	DN_FILA IS 'Filler' , 
	DN_GRS IS 'Gross' , 
	DN_ACC IS 'Acc' , 
	DN_DNU IS 'DNU' , 
	DN_CC IS 'CC' , 
	DN_FILB IS 'Filler' , 
	DN_CGC IS 'Cost                Code' , 
	DN_CGT IS 'Typ' , 
	DN_STA IS 'Sta' , 
	DN_ORD IS 'Stock #' , 
	DN_INV IS 'Inv #' , 
	DNFILD IS 'Filler' , 
	DN_PO IS 'PO #' , 
	DN_POBR IS 'PO                  Br' , 
	DN_CER IS 'Currency            Exchange            Rate' , 
	DN_DTI IS 'Inv Dte' , 
	DN_DTD IS 'G/L Date' , 
	DN_CUS IS 'Cus#' , 
	DN_TID IS 'TID#' , 
	DN_SEQ IS 'SEQ#' , 
	DN_UID IS 'UID#' , 
	DN_CHQ IS 'Check#' , 
	DN_HDES IS 'Hist' , 
	UPDATE_IDENT IS '  Update/           Identifier' ) ; 
  
LABEL ON COLUMN PFWF0125.YTDIST 
( DN_RID TEXT IS 'Record ID' , 
	DN_CO TEXT IS 'Company' , 
	DN_VEN TEXT IS 'Vendor Number' , 
	DN_DIV TEXT IS 'Division' , 
	DN_TC TEXT IS 'Transaction Code' , 
	DN_VCH TEXT IS 'Voucher Number' , 
	DN_NME TEXT IS 'Name' , 
	DN_RR TEXT IS 'Rapid Remittance, ADJ, REG' , 
	DN_FILA TEXT IS 'Filler' , 
	DN_GRS TEXT IS 'Gross' , 
	DN_ACC TEXT IS 'Account Number' , 
	DN_DNU TEXT IS 'Do Not Use (see PGM CCA007)' , 
	DN_CC TEXT IS 'Cost Center' , 
	DN_FILB TEXT IS 'Filler' , 
	DN_CGC TEXT IS 'Complete Goods Cost Code' , 
	DN_CGT TEXT IS 'Complete Goods Type' , 
	DN_STA TEXT IS 'Distribution Status' , 
	DN_ORD TEXT IS 'Stock Number' , 
	DN_INV TEXT IS 'Invoice Number' , 
	DNFILD TEXT IS 'Filler' , 
	DN_PO TEXT IS 'Purchase Order Number' , 
	DN_POBR TEXT IS 'Purchase Order Branch' , 
	DN_CER TEXT IS 'Currency Exchange Rate' , 
	DN_DTI TEXT IS 'Invoice Date CCYYMMDD' , 
	DN_DTD TEXT IS 'Distribution G/L Date CCYYMMDD' , 
	DN_CUS TEXT IS 'Customer Number' , 
	DN_TID TEXT IS 'TRANSACTION ID Number' , 
	DN_SEQ TEXT IS 'Sequence Number' , 
	DN_UID TEXT IS 'Update ID Number' , 
	DN_CHQ TEXT IS 'Check Number' , 
	DN_HDES TEXT IS 'History Description' , 
	UPDATE_IDENT TEXT IS 'Field update / access identifier' ) ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON PFWF0125.YTDIST TO PUBLIC WITH GRANT OPTION ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON PFWF0125.YTDIST TO QSECOFR WITH GRANT OPTION ; 
  
