--  Generate SQL 
--  Version:                   	V7R5M0 220415 
--  Generated on:              	05/31/26 09:19:35 
--  Relational Database:       	A12456DF 
--  Standards Option:          	Db2 for i 
CREATE TABLE PFWF0125.YTDJRL ( 
--  SQL150B   10   REUSEDLT(*NO) in table YTDJRL in PFWF0125 ignored. 
	YJ_JRL FOR COLUMN YJJRL      CHAR(4) CCSID 37 NOT NULL DEFAULT '' , 
	YJ_CC FOR COLUMN YJCC       CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	YJ_ACC FOR COLUMN YJACC      CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	YJ_FILA FOR COLUMN YJFILA     CHAR(3) CCSID 37 NOT NULL DEFAULT '' , 
	YJ_AMT FOR COLUMN YJAMT      NUMERIC(12, 2) NOT NULL DEFAULT 0 , 
	YJ_OSJ FOR COLUMN YJOSJ      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	YJ_RDT FOR COLUMN YJRDT      NUMERIC(6, 0) NOT NULL DEFAULT 0 , 
	YJ_RJRL FOR COLUMN YJRJRL     CHAR(4) CCSID 37 NOT NULL DEFAULT '' , 
	YJ_UID FOR COLUMN YJUID      DECIMAL(18, 0) NOT NULL DEFAULT 0 , 
	YJ_PDT FOR COLUMN YJPDT      NUMERIC(8, 0) NOT NULL DEFAULT 0 , 
	YJ_CO FOR COLUMN YJCO       CHAR(2) CCSID 37 NOT NULL DEFAULT '' , 
	YJ_DIV FOR COLUMN YJDIV      CHAR(2) CCSID 37 NOT NULL DEFAULT '' , 
	YJ_FILC FOR COLUMN YJFILC     CHAR(22) CCSID 37 NOT NULL DEFAULT '' , 
	YJ_DT FOR COLUMN YJDT       NUMERIC(8, 0) NOT NULL DEFAULT 0 , 
	YJ_FILD FOR COLUMN YJFILD     CHAR(2) CCSID 37 NOT NULL DEFAULT '' , 
	YJ_MEM FOR COLUMN YJMEM      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	YJ_SRC FOR COLUMN YJSRC      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	YJ_STA FOR COLUMN YJSTA      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	YJ_RID FOR COLUMN YJRID      CHAR(1) CCSID 37 NOT NULL DEFAULT '' , 
	YJ_USE FOR COLUMN YJUSE      CHAR(10) CCSID 37 NOT NULL DEFAULT '' , 
	YJ_CRT FOR COLUMN YJCRT      CHAR(10) CCSID 37 NOT NULL DEFAULT '' , 
	YJ_DES FOR COLUMN YJDES      CHAR(40) CCSID 37 NOT NULL DEFAULT '' , 
	UPDATE_IDENT FOR COLUMN @@UPID     DECIMAL(7, 0) NOT NULL DEFAULT 0 )   
	  
	RCDFMT YTDJRLR    ; 
  
--  SQL150A   30   System trigger QSYS_TRIG_PFWF0125___YTDJRL_____000001 in PFWF0125 ignored. 
--  SQL150A   30   System trigger QSYS_TRIG_PFWF0125___YTDJRL_____000002 in PFWF0125 ignored. 
--  SQL150A   30   System trigger QSYS_TRIG_PFWF0125___YTDJRL_____000003 in PFWF0125 ignored. 
LABEL ON TABLE PFWF0125.YTDJRL 
	IS 'Year To Date Journals' ; 
  
LABEL ON COLUMN PFWF0125.YTDJRL 
( YJ_JRL IS 'Jrnl#' , 
	YJ_CC IS 'Prof                Ctr' , 
	YJ_ACC IS 'Acc#' , 
	YJ_FILA IS 'Filler' , 
	YJ_AMT IS 'Amount' , 
	YJ_OSJ IS 'One                 Sided' , 
	YJ_RDT IS 'Reversal            Date' , 
	YJ_RJRL IS 'Rev                 Jrnl#' , 
	YJ_UID IS 'UID#' , 
	YJ_PDT IS 'Posting             Date' , 
	YJ_CO IS 'Co' , 
	YJ_DIV IS 'Div' , 
	YJ_FILC IS 'Filler' , 
	YJ_DT IS 'Date' , 
	YJ_FILD IS 'Filler' , 
	YJ_MEM IS 'Memo' , 
	YJ_SRC IS 'Source' , 
	YJ_STA IS 'Sta' , 
	YJ_RID IS 'RID' , 
	YJ_USE IS 'In                  Use' , 
	YJ_CRT IS 'Created             By User' , 
	YJ_DES IS 'Desc' , 
	UPDATE_IDENT IS '  Update/           Identifier' ) ; 
  
LABEL ON COLUMN PFWF0125.YTDJRL 
( YJ_JRL TEXT IS 'Journal Number' , 
	YJ_CC TEXT IS 'Prof Center' , 
	YJ_ACC TEXT IS 'Acc Number' , 
	YJ_FILA TEXT IS 'Filler' , 
	YJ_AMT TEXT IS 'Amount' , 
	YJ_OSJ TEXT IS 'One Sided Journal(" " or "Y")' , 
	YJ_RDT TEXT IS 'Reversal Date' , 
	YJ_RJRL TEXT IS 'Reversal Journal Number' , 
	YJ_UID TEXT IS 'Update ID Number' , 
	YJ_PDT TEXT IS 'Posting Date' , 
	YJ_CO TEXT IS 'Company' , 
	YJ_DIV TEXT IS 'Division' , 
	YJ_FILC TEXT IS 'Filler' , 
	YJ_DT TEXT IS 'Date' , 
	YJ_FILD TEXT IS 'Filler' , 
	YJ_MEM TEXT IS 'Memo' , 
	YJ_SRC TEXT IS 'Source' , 
	YJ_STA TEXT IS 'Status' , 
	YJ_RID TEXT IS 'Record ID' , 
	YJ_USE TEXT IS 'In Use' , 
	YJ_CRT TEXT IS 'Created By User' , 
	YJ_DES TEXT IS 'Desc' , 
	UPDATE_IDENT TEXT IS 'Field update / access identifier' ) ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON PFWF0125.YTDJRL TO PFWGP0125 WITH GRANT OPTION ; 
  
GRANT DELETE , INSERT , SELECT , UPDATE   
ON PFWF0125.YTDJRL TO PUBLIC WITH GRANT OPTION ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON PFWF0125.YTDJRL TO QOTHPRDOWN WITH GRANT OPTION ; 
  
GRANT DELETE , INSERT , SELECT , UPDATE   
ON PFWF0125.YTDJRL TO QSECOFR WITH GRANT OPTION ; 
  
